# .github/workflows/deploy.yml
name: Deploy Astro Site to GitHub Pages

on:
  # Trigger the workflow every time you push to the default branch (e.g. main)
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  content: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow multiple deployments to finish successfully.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install and Build (with Astro)
        uses: withastro/action@v1
        with:
          # path: .  # Optional, if your project is not in the root
          # packageManager: npm # Optional, detects automatically
          arguments: --remote
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment-url.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment-url
        uses: actions/deploy-pages@v4
